name: docker

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  release:
    types: [published]
  pull_request:
    branches:
      - 'master'

  workflow_dispatch: {}
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    name: "Docker image"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Install Docker BuildX
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            manifoldfinance/mev-gethx
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build
        uses: docker/bake-action@v2
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build
